### PR TITLE
feat(parser): make line count header optional

### PR DESCRIPTION
**Pull request by endes0**
For backward compatibility reasons, the code parser support an initial line indicating the number of lines of the code that was ignored **but required**. As @icasrod pointed, this line shouldn't be required at all. This PR fixes this and also updates the examples shown in the load code modals.

### CODE REVIEW

**Review by oxcabe — CHANGES_REQUESTED** [review]
Looking good so far. Add tests for both cases. Feel free to run biome on both parser files and, if possible, add some tsdoc documentation as well.

**Comment by endes0** [comment]
> Looking good so far. Add tests for both cases. Feel free to run biome on both parser files and, if possible, add some tsdoc documentation as well.

Done except for tsdoc, while it will be great I think it is outside this scope (and also, if I'm honest, I'm lazy ).

**Comment by oxcabe** [comment]
This is getting noisy, 36 comments, almost all of them from reviewdog :no_mouth:

**Comment by endes0** [comment]
> This is getting noisy, 36 comments, almost all of them from reviewdog 😶

yeah, first con of it.

**Review by oxcabe — APPROVED** [review]

**Pull request merged**
